### ISSUE TITLE
Road to v1

### ISSUE THREAD

**Issue by cmcaine** [JuliaWeb/Mux.jl#126]
This is an issue to collect ideas on what needs to be done to get this package to v1.

Here are some of my ideas:

 - [ ] add docstrings and a small manual #28
 - [ ] support HTTPS #25
 - [ ] more test coverage
   - [ ] we don't test examples/files.jl (the only security-relevant code ;)
   - [ ] or that `@app` allows hot reloading
 - [ ] make `wait(serve(app))` respond to SIGINT better
   - I can't kill a server started with `julia myserver.jl` with ctrl-c
 - [ ] make sure `do` syntax works in the places we would expect it to
   - e.g. both `page(app, path)` and `page(path, app)` are defined, so we can use it there, though it's a little bit weird that we have both
 - [ ] provide the original `HTTP.Request` in the `req` dict?
 - [ ] decide if `files()` should URL decode the given path by default #105
   - I think it should
 - [ ] nicer stacktraces #87
   - in the common case that `@app` gets a tuple, we could make the macro save the identity and names of each somewhere and the error catcher could re-write the stacktrace with that info?
 - [ ] maybe some more routing options/branches? (#38, #41, #54)
   - It's pretty easy to do yourself, but there are a few issues looking for helper functions something like these:
     - e.g. `branch(req -> predicate(req[:uri]), app)`
     - e.g. `branch(req -> predicate(req[:cookies]), app)`
     - e.g. `branch(req -> predicate(req[:headers]), app)`
     - e.g. `branch(req -> req[:uri].scheme == scheme, app)`
   - Maybe we can just document this better.
 - [ ] check performance? (#92)
   - mux should be viable for small, low-latency queries too, if possible
   - [ ] multiprocessing or multithreading support
   - it would be sad if you find you need better performance and it turns out Mux has some show-stoppers that mean you have to re-write in another framework.
   - [ ] possibly related: decide if Mux should support `HTTP.Request` or whether users must provide their own code for that #91
     - I think a struct with fields `req` and `state` or something might be good?
     - Mux doesn't let you return your own HTTP.Response objects, either, though that is very easy to add.
 - [ ] Decide if relative paths should be relative to the script file or the working directory #26
   - we can do it with `isabspath(root) || (root = joinpath(@__DIR__, root))`
   - Here be security dragons

Please add your ideas, too!

Related: #41 (GSoC 2017 ideas)

**Comment by cmcaine** [comment]
v1 was released without discussion, so any breaking changes can now be in Mux 2.0, I guess.
